employeemastersystem/emastersystem/urls.py
from django .urls import path
from emastersystem import views
urlpatterns=[
    path("",views.IndexView.as_view(),name='index'),
    path('account/signup',views.SignUpView.as_view(),name='signup'),
    path('account/signin', views.LoginView.as_view(), name='login'),
    path('account/signout',views.SignOut,name='signout'),
    path('users/profiles',views.ViewMyProfileView.as_view(),name='viewprofile'),
    path('bio', views.UserProfileAdd.as_view(), name='addpro'),
    path('user/profile/change/ <str:user_id>', views.UserUpdateView.as_view(), name='changeprofile'),
    path('all',views.EmployeeListView.as_view(),name='emp_list'),

    ]

employeemastersystem/employeemastersystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employe/', include('emastersystem.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employeemastersystem/emastersystem/models.py
from django.db import models
from django .contrib.auth .models import User
import random
# Create your models here.
class Employee(models.Model):
    about=models.CharField(max_length=120)
    designation = models.CharField(max_length=80)
    company= models.CharField(max_length=120,null=True)
    yearofexperience = models.PositiveIntegerField(null=True)
    description=models.CharField(max_length=150,null=True)
    image= models.ImageField(upload_to='profilepics', null=True)
    phone = models.CharField(max_length=20)
    date_of_birth = models.DateField(null=True)
    options = (
        ('male', 'male'),
        ('female', 'female'),
        ('other', 'other')
    )
    gender = models.CharField(max_length=12, choices=options, default='male')
    address=models.CharField(max_length=120)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='users')

employeemastersystem/emastersystem/forms.py
from django import forms
from django.forms import ModelForm
from emastersystem.models import Employee
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
class UserRegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=[
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2',
        ]

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField()

class UserProfileForm(ModelForm):
    class Meta:
        model=Employee
        exclude=('user',)
        widgets={
            'date_of_birth':forms.DateInput(attrs={'type':'date'})
        }

employeemastersystem/emastersystem/views.py
from django.shortcuts import render,redirect
from emastersystem.models import Employee
from django.views.generic import CreateView,FormView,TemplateView,UpdateView,View
from emastersystem.forms import UserProfileForm,UserCreationForm,LoginForm,UserRegistrationForm
from django .contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib import messages
from emastersystem.models import Employee
from django.utils.decorators import method_decorator
# Create your views here.


def signin_required(fuctn):
    def wrapper(request,*args,**kwargs):
        if request.user.is_authenticated:
            return fuctn(request,*args,**kwargs)
        else:
            messages.error(request,'Sigin First')
            return  redirect('login')
    return wrapper

class SignUpView(CreateView):
    form_class=UserRegistrationForm
    template_name = 'signup.html'
    model=User
    success_url = reverse_lazy('login')

class LoginView(FormView):
    form_class = LoginForm
    template_name='login.html'
    model=User
    def get(self,request,*args,**kwargs):
        return render(request,'login.html')
    def post(self,request,*args,**kwargs):
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        admin=authenticate(request,username='admin',password='admin')
        if user:
            print('success')
            login(request,user)
            return redirect('viewprofile')
        
        else:
            return render(request,'login.html')

class ViewMyProfileView(TemplateView):
    template_name = 'viewprofile.html'
class IndexView(TemplateView):
    template_name = 'index.html'

@method_decorator(signin_required,name='dispatch')
class UserProfileAdd(CreateView):
    form_class=UserProfileForm
    template_name ='addprofile.html'
    model = Employee
    print('success')
    success_url=reverse_lazy('viewprofile')
    def form_valid(self,form):
        form.instance.user=self.request.user
        print(form.instance.user)
        self.object=form.save()
        messages.success(self.request, 'profile added')
        return super().form_valid(form)

@method_decorator(signin_required,name='dispatch')
class UserUpdateView(UpdateView):
    model=Employee
    form_class = UserProfileForm
    template_name ='editprofile.html'
    success_url = reverse_lazy('viewprofile')
    pk_url_kwarg ='user_id'
    def form_valid(self, form):
        messages.success(self.request,'your profile updated Successfully')
        self.object = form.save()
        return super().form_valid(form)

@method_decorator(signin_required,name='dispatch')
class EmployeeListView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'employelist.html'
    success_url = reverse_lazy('emp_list')
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        employe=Employee.objects.all()
        context['employe']=employe
        return context




@signin_required
def SignOut(request,*args,**kwargs):
    logout(request)
    return redirect('login')

employeemastersystem/emastersystem/templates/addprofile.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AddProfile</title>
    <script src="https://kit.fontawesome.com/61d8d73bb4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{%static 'css/addprofile.css'%}">
    <link rel="stylesheet" href="{%static 'css/editprofile.css' %}">
</head>
<body>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">{{form.errors}}</div>
    <div class="col-4"></div>
</div>
<div id="page" class="site">
     <div class="container">
    <div class="wrapper">
     <div class="signup">
            <div class="content-heading">
                <div class="y-style">
                    <div class="logo">

                    </div>
                    <div class="welcome">
                        <h2>Add Here!!. <br></h2>
                        <p></p>

                    </div>
                </div>
            </div>

            <div class="content-form">
                <div class="y-style">
                    <form action="" method="post" enctype="multipart/form-data">
                        {%csrf_token%}





                        <p>
                            <label >About</label>
                            <input type="text" name="about" id="id_about"  placeholder="Enter Your Bio Here">
                        </p>
                         <p>
                            <label >Designation</label>
                            <input type="text" name="designation" id="id_designation"  placeholder="Enter Your Designation">
                        </p>
                        <p>
                            <label >Company</label>
                            <input type="text" name="company" id="id_company"  placeholder="Enter Your Company Name">
                        </p>
                        <p>
                            <label >Year Of Experience</label>
                            <input type="number" name="yearofexperience" id="id_yearofexperience"  placeholder="Enter Your Experience">
                        </p>
                        <p>
                            <label >Description</label>
                            <input type="text" name="description" id="id_description"  placeholder="Enter Your Job Description">
                        </p>
                        <p>
                            <label >Address</label>
                            <input type="text" name="address" id="id_address"  placeholder="Enter Your Address">
                        </p>
                        <p>
                            <label >Phone</label>
                            <input type="number" name="phone" id="id_phone"  placeholder="Enter Your Phone Number">
                        </p>
                         <p>
                            <label >Date Of Birth</label>
                            <input type="date" name="date_of_birth" id="id_date_of_birth" >
                        </p>

                        <p>
                            <label >Upload Image</label>
                            <input type="file" name="image" id="id_image">
                        </p>

                        <p>
                            <label >Gender</label><br>
                            <select id="id_gender" name="gender" class="form-control" style="width:100%; outline: 0;
    margin: 0 0 20px;
    padding: 10px 15px;
    border-radius: 7px;
    border: 1px solid var(--light-color);">
                                <option value="male">Male</option>
                                <option value="female">Female</option>
                                <option value="other">other</option>

                              </select>

                        </p>
                        <p class="check">
                            <input type="checkbox" id="terms">
                            <label for="condition">Publish profile</label>
                        </p>



                        <p><button type="submit">Add Profile Details</button> </p>
                    </form>

                </div>
            </div>








        </div>
 </div>
     </div>
</div>
</body>
</html>

employeemastersystem/emastersystem/templates/editprofile.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'css/editprofile.css' %}">
    <!-- font awosome -->
  <script src="https://kit.fontawesome.com/61d8d73bb4.js" crossorigin="anonymous"></script>
</head>
<body>
<div id="page" class="site">
    <div class="container">
        <div class="wrapper">
            <div class="signup">
                <div class="content-heading">
                    <div class="y-style">
                        <div class="logo">

                        </div>
                        <div class="welcome">
                            <h2>Update Here!!. <br></h2>
                            <p></p>

                        </div>
                    </div>
                </div>

                <div class="content-form">
                    <div class="y-style">
                        <form action="" method="post" enctype="multipart/form-data">
                            {%csrf_token%}

                            {{form.as_p}}


                            <p>
                                <button type="submit">Update Details</button>
                            </p>
                        </form>

                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
</body>
</html>

employeemastersystem/emastersystem/templates/employelist.html
<!DOCTYPE html>
{%load static%}
<!-- Created By CodingLab - www.codinglabweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-----<title>Responsive Profile Cards | CodingLab</title>----->
    <link rel="stylesheet" href="{%static 'css/employelist.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{%url 'viewprofile'%}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{%url 'signout'%}">Logout</a>
        </li>
      </ul>
      <form class="d-flex">
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->

      </form>
    </div>
  </div>
</nav>



    <div class="container">
      {%for emp in employe%}
      <div class="box">
      <div class="image">
        <img src="{{emp.user.users.image.url}}">
        </div>
        <div class="name_job">{{emp.user.first_name}}</div>
        <div class="rating">
        <b>{{emp.user.users.designation}}</b>
        </div>
        <p> {{emp.user.users.about}}</p>

      </div>
      {%endfor%}

    </div>
      </body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

employeemastersystem/emastersystem/templates/index.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Full Width Pics - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
       <link rel="stylesheet" href="{%static 'css/index.css' %}">
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'login'%}">SignIn</a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'signup'%}">SignUp</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header - set the background image for the header in the line below-->
        <header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
            <div class="text-center my-5">
                <img class="img-fluid rounded-circle mb-4" src="{%static 'images/emplom.jpg'%}" alt="..." />
                <h1 class="text-white fs-3 fw-bolder">Star Software Technology</h1>
                <p class="text-white-50 mb-0">Since 2009</p>
            </div>
        </header>
        <!-- Content section-->
        <section class="py-5">
            <div class="container my-5">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <h2>WE CREATE UNIQUE, SECURE, AND EFFICIENT SOLUTIONS THAT EMPOWERS AND ENCOURAGE YOUR BUSINESS</h2>
                        <p class="lead">Star Software Technology and Software is an offshore development centre focused on providing quality technology solutions for a global customer base. Our passion for technology and quality has pushed our success growth chart to higher peaks spanning over 18 years. </p>
                        <p class="mb-0">Leveraging our experience and expertise in Microsoft, Sun and Open-Source Technologies, we are committed to deliver sustainable IT solutions and support that will help to advance business and get ahead of the competition..</p>
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

employeemastersystem/emastersystem/templates/login.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <!-- font awosome -->
    <script src="https://kit.fontawesome.com/61d8d73bb4.js" crossorigin="anonymous"></script>
</head>
<body>

<div id="page" class="site login-show">
    <div class="container">
        <div class="wrapper">
            <div class="login">
                <div class="content-heading">
                    <div class="y-style">
                        <div class="logo">

                        </div>
                        <div class="welcome">
                            <h2>Login <br>Now! </h2>
                            <p>Get start Creative.</p>

                        </div>
                    </div>
                </div>

                <div class="content-form">
                    <div class="y-style">
                        <form action="" method="post">
                            {%csrf_token%}
                            <p>
                                <label>Username</label>
                                <input type="text" placeholder="Enter Your Username" name="username" id=" id_username">
                            </p>
                            <p>
                                <label>Password</label>
                                <input type="password" placeholder="Enter Your Password" name="password" id=" id_password">
                            </p>
                            <p class="check">
                                <input type="checkbox" id="remember">
                                <label for="remember">Remember Password</label>
                            </p>
                            <p class="forgot"><a href="#">Forgot Password</a></p>
                            <p>
                                <button type="submit">Login</button>
                            </p>
                        </form>
                        <div class="afterform">
                            <p>Don't have account?</p>
                            <a href="{%url 'signup'%}" class="t-signup">Register</a>
                        </div>
                    </div>
                </div>







            </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

employeemastersystem/emastersystem/templates/signup.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'css/signup.css' %}">
    <!-- font awosome -->
  <script src="https://kit.fontawesome.com/61d8d73bb4.js" crossorigin="anonymous"></script>
</head>
<body>
<div class="row">
    <col-4></col-4>
    <col-4>{{form.errors}}</col-4>
    <col-4></col-4>
</div>
<div id="page" class="site">
     <div class="container">
    <div class="wrapper">
     <div class="signup">
            <div class="content-heading">
                <div class="y-style">
                    <div class="logo">

                    </div>
                    <div class="welcome">
                        <h2>Welcome <br>Back! </h2>
                        <p>Get start Creative.</p>

                    </div>
                </div>
            </div>

            <div class="content-form">
                <div class="y-style">
                    <form action="" method="post">
                        {%csrf_token%}


                        <p>
                            <label >FirstName</label>
                            <input type="text"  name= "first_name" id="id_first_name" placeholder="Enter Your Firstname">
                        </p>
                        <p>
                            <label >LastName</label>
                            <input type="text" name="last_name" id="id_last_name" placeholder="Enter Your Lastname">
                        </p>
                        <p>
                            <label >Email</label>
                            <input type="email" name="email" id="id_email"  placeholder="Enter Your Email">
                        </p>
                        <!-- <p>
                            <label >Mobile</label>
                            <input type="number"  placeholder="Enter Your Mobile Number">
                        </p> -->
                        <p>
                            <label >Username</label>
                            <input type="text" name="username" id="id_username" placeholder="Enter Your Username">
                        </p>
                        <p>
                            <label >Password</label>
                            <input type="password" name="password1" id="id_password1" placeholder="Enter Your Password">
                        </p>

                        <p>
                            <label >Confirm Password</label>
                            <input type="password"  name="password2" id="id_password2" placeholder="Confirm Password">
                        </p>
                        <p class="check">
                            <input type="checkbox" id="terms">
                            <label for="conditions">I agree the Terms and Conditions</label>
                        </p>


                        <!-- <p class="forgot"> <a href="#">Forgot Password</a> </p> -->
                        <p><button type="submit">SignUP</button> </p>
                    </form>
                    <div class="social">
                        <p> <span> Or Signup With</span></p>
                        <ul>
                            <li> <a href="#" class="google"><i class="fa-brands fa-google"></i></a></i></li>
                            <li> <a href="#" class="facebook"><i class="fa-brands fa-facebook"></i></a> </i></li>
                            <li> <a href="#" class="twitter"><i class="fa-brands fa-twitter"></i></a></i></li>
                        </ul>
                    </div>
                    <div class="afterform">
                        <p>Already have  an account?</p>
                        <a href="{%url 'login'%}" class="t-signup">Login  Here</a>
                    </div>
                </div>
            </div>
        </div>
 </div>
     </div>
</div>

</body>
</html>

employeemastersystem/emastersystem/templates/viewprofile.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Resume - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{%static 'css/viewprofile.css' %}">
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">{{request.user}}</span>
                {%if request.user.users.image%}
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{{request.user.users.image.url}}" alt="..." /></span>
            {%endif%}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                     {%if request.user.users%}
                     <li class="nav-item"><a class="nav-link " href="{%url 'changeprofile' request.user.users.id %}">Edit Profile</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#experience">Other Details</a></li>
                    {%else%}
                    <li class="nav-item"><a class="nav-link " href="{%url 'addpro'%}">Add Profile</a></li>
                    {%endif%}
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{%url 'emp_list'%}">Employe List</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{%url 'signout'%}">Logout</a></li>
                </ul>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container-fluid p-0">
            <!-- About-->
            <section class="resume-section" id="about">
                <div class="resume-section-content">
                    <h1 class="mb-0">
                       {{request.user.first_name}}
                        <span class="text-primary">{{request.user.last_name}}</span>
                    </h1>
                    <h6>{{request.user.users.about}}</h6>
                    <br>
                    <p><h3 class="mb-0"> Official Details</h3></p>
                      <h4 class="mb-0">{{request.user.users.designation}}</h4>
                    <div class="subheading mb-5">
                       <i class="fa-solid fa-briefcase"></i>{{request.user.users.company}} <br>

                        <a href="{{request.user.email}}"><i class="fa-solid fa-envelope"></i>"{{request.user.email}}"</a>
                       <br>
                        <i class="fa-solid fa-phone"></i>{{request.user.users.phone}} <br>
                        <i class="fa-solid fa-location-dot"></i>{{request.user.users.address}}
                    </div>
                    <div class="subheading mb-5">

                        </div>
                    <p class="lead mb-5"></p>

                    <div class="flex-grow-1">
                            <h3 class="mb-0"></h3>
                            <div class="subheading mb-3"></div>
                            <p></p>
                        </div>

                    <div class="flex-grow-1">
                            <h3 class="mb-0">Experience</h3>
                            <div class="subheading mb-3">{{request.user.users.description}}</div>
                            <p>.</p>
                        </div>

                    <div class="social-icons">
                        <a class="social-icon" href="#!"><i class="fab fa-linkedin-in"></i></a>
                        <a class="social-icon" href="#!"><i class="fab fa-github"></i></a>
                        <a class="social-icon" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="social-icon" href="#!"><i class="fab fa-facebook-f"></i></a>
                    </div>
                </div>
            </section>
            <hr class="m-0" />
            <section class="resume-section" id="experience">
                <div class="resume-section-content">
                    <h2 class="mb-5">Personal Details</h2>
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <br>
                              <h5 class="mb-0"><i class="fa-solid fa-location-dot"></i>Address:{{request.user.users.address}}</h5>
                            <br>
                                <h5 class="mb-0"><i class="fa-solid fa-cake-candles"></i>Date Of Birth:{{request.user.users.date_of_birth}}</h5>
                            <br>
                                <h5 class="mb-0"><i class="fa-solid fa-person-half-dress"></i>Gender:{{request.user.users.gender}}</h5>


                        </div>

                    </div>
                </div>
            </section>
            <hr class="m-0" />




        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>